// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: wfl.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicType int32

const (
	TopicType_NONE  TopicType = 0 // proto3版本中，首成员必须为0，成员不应有相同的值
	TopicType_EVENT TopicType = 1 // 事件处理
	TopicType_PUSH  TopicType = 2 // 推送
)

// Enum value maps for TopicType.
var (
	TopicType_name = map[int32]string{
		0: "NONE",
		1: "EVENT",
		2: "PUSH",
	}
	TopicType_value = map[string]int32{
		"NONE":  0,
		"EVENT": 1,
		"PUSH":  2,
	}
)

func (x TopicType) Enum() *TopicType {
	p := new(TopicType)
	*p = x
	return p
}

func (x TopicType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopicType) Descriptor() protoreflect.EnumDescriptor {
	return file_wfl_proto_enumTypes[0].Descriptor()
}

func (TopicType) Type() protoreflect.EnumType {
	return &file_wfl_proto_enumTypes[0]
}

func (x TopicType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopicType.Descriptor instead.
func (TopicType) EnumDescriptor() ([]byte, []int) {
	return file_wfl_proto_rawDescGZIP(), []int{0}
}

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier int32  `protobuf:"varint,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Operation  string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	MsgId      string `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Req_SendMsgReq
	//	*Req_PullMsgBySeqListReq
	//	*Req_MaxAndMinSeqReq
	Data isReq_Data `protobuf_oneof:"data"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wfl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_wfl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_wfl_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetIdentifier() int32 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *Req) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Req) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (m *Req) GetData() isReq_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Req) GetSendMsgReq() *SendMsgReq {
	if x, ok := x.GetData().(*Req_SendMsgReq); ok {
		return x.SendMsgReq
	}
	return nil
}

func (x *Req) GetPullMsgBySeqListReq() *PullMsgBySeqListReq {
	if x, ok := x.GetData().(*Req_PullMsgBySeqListReq); ok {
		return x.PullMsgBySeqListReq
	}
	return nil
}

func (x *Req) GetMaxAndMinSeqReq() *GetMsgMaxAndMinSeqReq {
	if x, ok := x.GetData().(*Req_MaxAndMinSeqReq); ok {
		return x.MaxAndMinSeqReq
	}
	return nil
}

type isReq_Data interface {
	isReq_Data()
}

type Req_SendMsgReq struct {
	SendMsgReq *SendMsgReq `protobuf:"bytes,4,opt,name=sendMsgReq,proto3,oneof"`
}

type Req_PullMsgBySeqListReq struct {
	PullMsgBySeqListReq *PullMsgBySeqListReq `protobuf:"bytes,5,opt,name=pullMsgBySeqListReq,proto3,oneof"`
}

type Req_MaxAndMinSeqReq struct {
	MaxAndMinSeqReq *GetMsgMaxAndMinSeqReq `protobuf:"bytes,6,opt,name=maxAndMinSeqReq,proto3,oneof"`
}

func (*Req_SendMsgReq) isReq_Data() {}

func (*Req_PullMsgBySeqListReq) isReq_Data() {}

func (*Req_MaxAndMinSeqReq) isReq_Data() {}

type SendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event string    `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Data  []byte    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Topic TopicType `protobuf:"varint,3,opt,name=topic,proto3,enum=TopicType" json:"topic,omitempty"`
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wfl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_wfl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_wfl_proto_rawDescGZIP(), []int{1}
}

func (x *SendMsgReq) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *SendMsgReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendMsgReq) GetTopic() TopicType {
	if x != nil {
		return x.Topic
	}
	return TopicType_NONE
}

// @send recruit.query.pool
type RecruitQueryPoolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 招募卡池id
}

func (x *RecruitQueryPoolReq) Reset() {
	*x = RecruitQueryPoolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wfl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecruitQueryPoolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecruitQueryPoolReq) ProtoMessage() {}

func (x *RecruitQueryPoolReq) ProtoReflect() protoreflect.Message {
	mi := &file_wfl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecruitQueryPoolReq.ProtoReflect.Descriptor instead.
func (*RecruitQueryPoolReq) Descriptor() ([]byte, []int) {
	return file_wfl_proto_rawDescGZIP(), []int{2}
}

func (x *RecruitQueryPoolReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PullMsgBySeqListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullMsgBySeqListReq) Reset() {
	*x = PullMsgBySeqListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wfl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMsgBySeqListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMsgBySeqListReq) ProtoMessage() {}

func (x *PullMsgBySeqListReq) ProtoReflect() protoreflect.Message {
	mi := &file_wfl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMsgBySeqListReq.ProtoReflect.Descriptor instead.
func (*PullMsgBySeqListReq) Descriptor() ([]byte, []int) {
	return file_wfl_proto_rawDescGZIP(), []int{3}
}

type GetMsgMaxAndMinSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMsgMaxAndMinSeqReq) Reset() {
	*x = GetMsgMaxAndMinSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wfl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMsgMaxAndMinSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMsgMaxAndMinSeqReq) ProtoMessage() {}

func (x *GetMsgMaxAndMinSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_wfl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMsgMaxAndMinSeqReq.ProtoReflect.Descriptor instead.
func (*GetMsgMaxAndMinSeqReq) Descriptor() ([]byte, []int) {
	return file_wfl_proto_rawDescGZIP(), []int{4}
}

var File_wfl_proto protoreflect.FileDescriptor

var file_wfl_proto_rawDesc = []byte{
	0x0a, 0x09, 0x77, 0x66, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x02, 0x0a, 0x03,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x48, 0x0a, 0x13, 0x70, 0x75, 0x6c, 0x6c, 0x4d, 0x73,
	0x67, 0x42, 0x79, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x53,
	0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x13, 0x70, 0x75, 0x6c,
	0x6c, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x42, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x41, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x53, 0x65, 0x71,
	0x52, 0x65, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x73, 0x67, 0x4d, 0x61, 0x78, 0x41, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x52, 0x65,
	0x71, 0x48, 0x00, 0x52, 0x0f, 0x6d, 0x61, 0x78, 0x41, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x53, 0x65,
	0x71, 0x52, 0x65, 0x71, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x58, 0x0a, 0x0a,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x15, 0x0a,
	0x13, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x4d, 0x61,
	0x78, 0x41, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x2a, 0x2a, 0x0a,
	0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x55, 0x53, 0x48, 0x10, 0x02, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wfl_proto_rawDescOnce sync.Once
	file_wfl_proto_rawDescData = file_wfl_proto_rawDesc
)

func file_wfl_proto_rawDescGZIP() []byte {
	file_wfl_proto_rawDescOnce.Do(func() {
		file_wfl_proto_rawDescData = protoimpl.X.CompressGZIP(file_wfl_proto_rawDescData)
	})
	return file_wfl_proto_rawDescData
}

var file_wfl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wfl_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wfl_proto_goTypes = []interface{}{
	(TopicType)(0),                // 0: TopicType
	(*Req)(nil),                   // 1: Req
	(*SendMsgReq)(nil),            // 2: SendMsgReq
	(*RecruitQueryPoolReq)(nil),   // 3: RecruitQueryPoolReq
	(*PullMsgBySeqListReq)(nil),   // 4: PullMsgBySeqListReq
	(*GetMsgMaxAndMinSeqReq)(nil), // 5: GetMsgMaxAndMinSeqReq
}
var file_wfl_proto_depIdxs = []int32{
	2, // 0: Req.sendMsgReq:type_name -> SendMsgReq
	4, // 1: Req.pullMsgBySeqListReq:type_name -> PullMsgBySeqListReq
	5, // 2: Req.maxAndMinSeqReq:type_name -> GetMsgMaxAndMinSeqReq
	0, // 3: SendMsgReq.topic:type_name -> TopicType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wfl_proto_init() }
func file_wfl_proto_init() {
	if File_wfl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wfl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wfl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wfl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecruitQueryPoolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wfl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMsgBySeqListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wfl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMsgMaxAndMinSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_wfl_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Req_SendMsgReq)(nil),
		(*Req_PullMsgBySeqListReq)(nil),
		(*Req_MaxAndMinSeqReq)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wfl_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wfl_proto_goTypes,
		DependencyIndexes: file_wfl_proto_depIdxs,
		EnumInfos:         file_wfl_proto_enumTypes,
		MessageInfos:      file_wfl_proto_msgTypes,
	}.Build()
	File_wfl_proto = out.File
	file_wfl_proto_rawDesc = nil
	file_wfl_proto_goTypes = nil
	file_wfl_proto_depIdxs = nil
}
